export type JSQuestion = {
  savol: string;
  a: string;
  b: string;
  c: string;
  d: string;
  correct_answer: 'a' | 'b' | 'c' | 'd';
};

export const jsQuestions: JSQuestion[] = [
  {
    savol: " JavaScript-da 'this' kalit so‘zi global scope’da nimani bildiradi?",
    a: "window obyektini",
    b: "function o‘zini",
    c: "undefined",
    d: "document obyektini",
    correct_answer: "a",
  },
  {
    savol: " let va var o‘rtasidagi asosiy farq nima?",
    a: "let block scope, var function scope",
    b: "let faqat function ichida ishlaydi",
    c: "var faqat global scope’da ishlaydi",
    d: "farqi yo‘q",
    correct_answer: "a",
  },
  {
    savol: " async/await nima uchun ishlatiladi?",
    a: "DOM bilan ishlash uchun",
    b: "massivlar bilan ishlash uchun",
    c: "asinxron kodni sinxron sintaksisda yozish uchun",
    d: "CSS manipulyatsiya qilish uchun",
    correct_answer: "c",
  },
  {
    savol: " JavaScript-da 'Promise' qanday ishlaydi?",
    a: "Asinxron natijani bildiradi",
    b: "Massivni bildiradi",
    c: "DOM elementni bildiradi",
    d: "Callback funksiyani chaqiradi",
    correct_answer: "a",
  },
  {
    savol: " 'use strict' rejimi nimani anglatadi?",
    a: "Kodni avtomatik optimallashtiradi",
    b: "Sintaksis xatoliklarni ko‘rsatmaydi",
    c: "Kodni qat'iyroq bajarishga majbur qiladi",
    d: "Let o‘zgaruvchilari bloklanadi",
    correct_answer: "c",
  },
  {
    savol: " typeof null qiymati nima bo‘ladi?",
    a: "null",
    b: "object",
    c: "undefined",
    d: "boolean",
    correct_answer: "b",
  },
  {
    savol: " setTimeout(callback, 0) qanday ishlaydi?",
    a: "Hech qachon bajarilmaydi",
    b: "Darhol bajariladi",
    c: "Call stack bo‘shaganda bajariladi",
    d: "Timer tugagach bajariladi",
    correct_answer: "c",
  },
  {
    savol: "JavaScript-da function declaration va expression o‘rtasidagi farq nima?",
    a: "Ikkisi bir xil",
    b: "Expression hoisting qilinmaydi",
    c: "Declaration faqat const bilan ishlaydi",
    d: "Expression return qilmaydi",
    correct_answer: "b",
  },
  {
    savol: "Array.prototype.map() nima qiladi?",
    a: "Elementlarni o‘chiradi",
    b: "Filtrlab beradi",
    c: "Yangi massiv qaytaradi",
    d: "Massivni sort qiladi",
    correct_answer: "c",
  },
  {
    savol: "Spread operator nima vazifani bajaradi?",
    a: "Elementlarni ko‘paytiradi",
    b: "Elementlarni ajratadi",
    c: "Elementlarni klonlaydi",
    d: "Elementlarni qo‘shadi",
    correct_answer: "c",
  },


  {
    savol: "JavaScript-da NaN === NaN natijasi nima bo‘ladi?",
    a: "true",
    b: "false",
    c: "Error",
    d: "undefined",
    correct_answer: "b",
  },
  {
    savol: "DOM nima?",
    a: "Database Object Model",
    b: "Document Object Model",
    c: "Design Order Model",
    d: "Disk Operation Mode",
    correct_answer: "b",
  },
  {
    savol: "Closure nima?",
    a: "Function ichidagi boshqa function",
    b: "Variable’ni yopib qo‘yish usuli",
    c: "Function o‘z scope’si bilan qaytishi",
    d: "Event Listener",
    correct_answer: "c",
  },
  {
    savol: "'===' operatori qanday ishlaydi?",
    a: "Faqat qiymatni solishtiradi",
    b: "Qiymat va tipni solishtiradi",
    c: "Tipni konvertatsiya qiladi",
    d: "Stringlarni taqqoslaydi",
    correct_answer: "b",
  },
  {
    savol: "JavaScript single-threaded tilmi?",
    a: "Yo‘q, multi-threaded",
    b: "Ha, asinxron",
    c: "Ha, single-threaded",
    d: "Hech biri emas",
    correct_answer: "c",
  },
  {
    savol: "Which method removes the last element of an array?",
    a: "pop()",
    b: "shift()",
    c: "unshift()",
    d: "remove()",
    correct_answer: "a",
  },
  {
    savol: "Qaysi biri falsy qiymat emas?",
    a: "0",
    b: "''",
    c: "undefined",
    d: "'false'",
    correct_answer: "d",
  },
  {
    savol: "Which one triggers only once?",
    a: "addEventListener('click', fn)",
    b: "addEventListener('click', fn, { once: true })",
    c: "setInterval(fn, 1000)",
    d: "setTimeout(fn, 0)",
    correct_answer: "b",
  },
  {
    savol: "Function’lar default parameterga ega bo‘lishi mumkinmi?",
    a: "Yo‘q",
    b: "Faqat arrow functionlarda",
    c: "Ha",
    d: "ES6dan keyin emas",
    correct_answer: "c",
  },
  {
    savol: "document.querySelectorAll() nima qaytaradi?",
    a: "Element",
    b: "NodeList",
    c: "Array",
    d: "String",
    correct_answer: "b",
  },
{
  savol: "typeof [] qiymati nima?",
  a: "array",
  b: "object",
  c: "null",
  d: "undefined",
  correct_answer: "b",
},
{
  savol: "'event.preventDefault()' nima qiladi?",
  a: "Elementni yashiradi",
  b: "Eventni to‘xtatadi",
  c: "Formani yuborishni to‘xtatadi",
  d: "Eventni qayta boshlaydi",
  correct_answer: "c",
},
{
  savol: "setInterval nima qiladi?",
  a: "Kodning bajarilishini kechiktiradi",
  b: "Berilgan intervalda qayta-qayta bajaradi",
  c: "Faqat bir marta bajaradi",
  d: "Kod blokini tozalaydi",
  correct_answer: "b",
},
{
  savol: "try/catch blokida finally bo‘limining vazifasi nima?",
  a: "xatoni log qiladi",
  b: "doim bajariladi",
  c: "try ni to‘xtatadi",
  d: "xatoni throw qiladi",
  correct_answer: "b",
},
{
  savol: "LocalStorage bilan SessionStorage o‘rtasidagi farq nima?",
  a: "LocalStorage faqat mobilda ishlaydi",
  b: "SessionStorage doimiy saqlanadi",
  c: "LocalStorage ma’lumotni uzoq muddat saqlaydi",
  d: "Ikkalasi ham bir xil",
  correct_answer: "c",
},
{
  savol: "let bilan e’lon qilingan o‘zgaruvchi qayta aniqlanadimi?",
  a: "Ha",
  b: "Yo‘q",
  c: "Agar global bo‘lsa, ha",
  d: "Faqat function ichida",
  correct_answer: "b",
},
{
  savol: "Function call'da bind() metodi nima uchun ishlatiladi?",
  a: "this ni belgilash uchun",
  b: "objectni yaratish uchun",
  c: "callbackni yoqish uchun",
  d: "arrayni o‘zgartirish uchun",
  correct_answer: "a",
},
{
  savol: "Arrow functionlarda 'this' qanday ishlaydi?",
  a: "doim globalga bog‘lanadi",
  b: "chaqirilgan joyga qarab o‘zgaradi",
  c: "this ishlatilmaydi",
  d: "parent scope’dan oladi",
  correct_answer: "d",
},
{
  savol: "DOM event delegation nima?",
  a: "Eventni o‘chirib qo‘yish",
  b: "Parent orqali eventni ushlash",
  c: "Har bir elementga event biriktirish",
  d: "DOMni tozalash",
  correct_answer: "b",
},
{
  savol: "Optional chaining operatori qanday ishlaydi?",
  a: "?",
  b: "??",
  c: "?.",
  d: "&&",
  correct_answer: "c",
},
{
  savol: "window.alert() nima qiladi?",
  a: "Konsolga chiqaradi",
  b: "Alert oynasini ko‘rsatadi",
  c: "DOM ni yangilaydi",
  d: "Formani yuboradi",
  correct_answer: "b",
},
{
  savol: "typeof undefined qiymati nima?",
  a: "null",
  b: "object",
  c: "undefined",
  d: "boolean",
  correct_answer: "c",
},
{
  savol: "Object.freeze() vazifasi nima?",
  a: "Objectni klonlaydi",
  b: "Objectni tahrirlashga yopadi",
  c: "Objectni arrayga aylantiradi",
  d: "Objectni o‘chiradi",
  correct_answer: "b",
},
{
  savol: "JavaScript-da function'lar birinchi tartibli (first-class) degani nima?",
  a: "Faqat return qilinadi",
  b: "Funksiya parametr sifatida uzatiladi",
  c: "Faqat top-level'da e’lon qilinadi",
  d: "Yuqorida aniqlanishi kerak",
  correct_answer: "b",
},
{
  savol: "JavaScript-da false qiymatni toping:",
  a: "''",
  b: "0",
  c: "null",
  d: "Barchasi",
  correct_answer: "d",
},
{
  savol: "Qaysi biri shallow copy beradi?",
  a: "JSON.stringify()",
  b: "Object.assign()",
  c: "deepClone()",
  d: "clone()",
  correct_answer: "b",
},
{
  savol: "Math.random() nima qiladi?",
  a: "Tasodifiy string qaytaradi",
  b: "0 va 1 orasida random son",
  c: "Faol foydalanuvchini tanlaydi",
  d: "To‘liq raqamlar ketma-ketligi",
  correct_answer: "b",
},
{
  savol: "Event bubbling nima degani?",
  a: "Child'dan parent'ga event o'tishi",
  b: "Eventni bosish",
  c: "Eventni to‘xtatish",
  d: "DOM'ni yangilash",
  correct_answer: "a",
},
{
  savol: "Promise.all() nima qiladi?",
  a: "Barcha promiseni ketma-ket bajaradi",
  b: "Promise'lar orasidan birinchisini tanlaydi",
  c: "Barchasini parallel bajaradi va kutadi",
  d: "Bir nechta callback chaqiradi",
  correct_answer: "c",
},
{
  savol: "map() va forEach() o‘rtasidagi farq nima?",
  a: "forEach yangi array qaytaradi",
  b: "map DOM bilan ishlaydi",
  c: "map yangi array qaytaradi",
  d: "farqi yo‘q",
  correct_answer: "c",
},
{
  savol: "typeof null nima uchun object beradi?",
  a: "Engine xatoligi",
  b: "To‘g‘ri qiymat",
  c: "TypeScript xatosi",
  d: "Compiler optimizatsiyasi",
  correct_answer: "a",
},
{
  savol: ".then() va await o‘rtasidagi bog‘liqlik nima?",
  a: "Ular har xil",
  b: "await .then()’ning syntactic sugari",
  c: "Ular promise bilan ishlamaydi",
  d: "Ular eventga bog‘liq",
  correct_answer: "b",
},
{
  savol: "JSON.parse() nima qiladi?",
  a: "JSON'ni objectga aylantiradi",
  b: "Object'ni JSON qiladi",
  c: "Objectni klonlaydi",
  d: "Stringdan raqam oladi",
  correct_answer: "a",
},
{
  savol: "typeof NaN qiymati nima bo‘ladi?",
  a: "NaN",
  b: "number",
  c: "undefined",
  d: "string",
  correct_answer: "b",
},
{
  savol: "Web API degani nima?",
  a: "Node.js funksiyasi",
  b: "Veb server",
  c: "Brauzer tomonidan taqdim etilgan API",
  d: "DOM'ga tegishli HTML",
  correct_answer: "c",
},
{
  savol: "innerHTML va textContent o‘rtasidagi farq nima?",
  a: "innerHTML faqat text",
  b: "textContent HTMLni o‘zgartiradi",
  c: "innerHTML HTMLni o‘zgartiradi",
  d: "farqi yo‘q",
  correct_answer: "c",
},
{
  savol: "Nullish coalescing operatori qanday belgilanadi?",
  a: "||",
  b: "&&",
  c: "??",
  d: "?=",
  correct_answer: "c",
},
{
  savol: "function foo(){} ni qanday chaqirasiz?",
  a: "foo",
  b: "foo[]",
  c: "foo()",
  d: "call foo",
  correct_answer: "c",
},
{
  savol: "JavaScript-da string immutable degani nima?",
  a: "o‘zgartirish mumkin",
  b: "read-only",
  c: "faqat const bilan ishlaydi",
  d: "string qiymatlari o‘zgartirilmaydi",
  correct_answer: "d",
},
{
  savol: "typeof function(){} qiymati nima?",
  a: "function",
  b: "object",
  c: "method",
  d: "undefined",
  correct_answer: "a",
}


];
